### ISSUE TITLE
Jamming Project Review: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [Bomingong/Codecademy#11]
### Criteria 1: App Creation, Folder Structure, and File Paths
* _Score Level:_ 4/4
* _Comment(s):_ Overall app folder structure and import/export file paths throughout the project look solid. I don't see any issues here.
 
### Criteria 2: Correct Implementation of User Flows (e.g. Searching, Token Generation, Save Playlist, etc.)
* _Score Level:_ 2/4
* _Comment(s):_ Overall, most of the functionality of the app works as expected. The only thing that doesn't seem to work properly is actually saving the playlist to Spotify (this seems to be an issues with a `POST` request to `https://api.spotify.com/v1/users/username/playlists/undefined/tracks`, which you can see has "undefined" in the route)
 
### Criteria 3: Proper JavaScript and JSX Syntax and Formatting
* _Score Level:_ 4/4
* _Comment(s):_ Awesome work with your JS/JSX syntax/formatting. I don't see any glaring issues here and you've included solid comments throughout the project as well.
 
### Criteria 4: Implementation Adheres to DRY Principles
* _Score Level:_ 4/4
* _Comment(s):_ I don't see any unnecessary/repeated code throughout the project.
 
### Overall Score: 14/16
The project is just about perfect. The only issue I was having was actually getting the playlist to save to a user account on Spotify, as mentioned. It looks like a `404` is happening in the current state of the application.

**Comment by Bomingong** [comment]
Hi Sid, 
Thanks for the feedback.  I haven't had a problem on my end with saving a playlist.  However, when I opened my app yesterday, the anchor tag to add and remove a track wasn't working, though I have fixed that problem (was missing () when calling this.renderAction()).  I might have submitted the wrong version, do you mind checking my updated repo to see if the save playlist issue is satisfactory?  If the redirect_uri was set to surge, I did realize that after I deployed, I had errors in my code but never redeployed to surge until recently (or is the term re-build?).

Thanks,
Chris
